const mockLabTests = [
  {
    id: "1",
    testName: "Complete Blood Count (CBC)",
    category: "blood",
    description: "Full blood panel including WBC, RBC, platelets",
    price: 45,
    turnaroundTime: "2-4 hours",
    requiresFasting: false,
    status: "active",
  },
  {
    id: "2",
    testName: "Lipid Panel",
    category: "blood",
    description: "Cholesterol and triglyceride levels",
    price: 55,
    turnaroundTime: "4-6 hours",
    requiresFasting: true,
    status: "active",
  },
  {
    id: "3",
    testName: "Urinalysis",
    category: "urine",
    description: "Complete urine analysis",
    price: 30,
    turnaroundTime: "1-2 hours",
    requiresFasting: false,
    status: "active",
  },
  {
    id: "4",
    testName: "Chest X-Ray",
    category: "imaging",
    description: "Standard chest radiograph",
    price: 120,
    turnaroundTime: "30 min",
    requiresFasting: false,
    status: "active",
  },
  {
    id: "5",
    testName: "MRI Brain",
    category: "imaging",
    description: "Magnetic resonance imaging of brain",
    price: 850,
    turnaroundTime: "1-2 days",
    requiresFasting: false,
    status: "active",
  },
  {
    id: "6",
    testName: "Biopsy Analysis",
    category: "pathology",
    description: "Tissue sample analysis",
    price: 200,
    turnaroundTime: "3-5 days",
    requiresFasting: false,
    status: "active",
  },
  {
    id: "7",
    testName: "Blood Sugar (Fasting)",
    category: "blood",
    description: "Fasting glucose test",
    price: 25,
    turnaroundTime: "1 hour",
    requiresFasting: true,
    status: "active",
  },
  {
    id: "8",
    testName: "Thyroid Panel",
    category: "blood",
    description: "TSH, T3, T4 levels",
    price: 85,
    turnaroundTime: "4-6 hours",
    requiresFasting: false,
    status: "inactive",
  },
];

const mockProcedures = [
  {
    id: "1",
    procedureName: "ECG/EKG",
    category: "diagnostic",
    description: "Electrocardiogram",
    price: 75,
    duration: "15 min",
    requiresAnesthesia: false,
    status: "active",
  },
  {
    id: "2",
    procedureName: "Echocardiogram",
    category: "diagnostic",
    description: "Ultrasound of heart",
    price: 350,
    duration: "45 min",
    requiresAnesthesia: false,
    status: "active",
  },
  {
    id: "3",
    procedureName: "Endoscopy",
    category: "diagnostic",
    description: "Upper GI examination",
    price: 800,
    duration: "30 min",
    requiresAnesthesia: true,
    status: "active",
  },
  {
    id: "4",
    procedureName: "Colonoscopy",
    category: "diagnostic",
    description: "Colon examination",
    price: 1200,
    duration: "45 min",
    requiresAnesthesia: true,
    status: "active",
  },
  {
    id: "5",
    procedureName: "Wound Suturing",
    category: "minor",
    description: "Minor wound closure",
    price: 150,
    duration: "20 min",
    requiresAnesthesia: true,
    status: "active",
  },
  {
    id: "6",
    procedureName: "Cardiac Catheterization",
    category: "major",
    description: "Heart catheter procedure",
    price: 5000,
    duration: "2 hours",
    requiresAnesthesia: true,
    status: "active",
  },
  {
    id: "7",
    procedureName: "Physical Therapy Session",
    category: "therapeutic",
    description: "1-hour therapy session",
    price: 120,
    duration: "1 hour",
    requiresAnesthesia: false,
    status: "active",
  },
  {
    id: "8",
    procedureName: "IV Infusion",
    category: "therapeutic",
    description: "Intravenous medication delivery",
    price: 85,
    duration: "30-60 min",
    requiresAnesthesia: false,
    status: "active",
  },
];